version: "2.22"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      DB: "mongodb://mongodb:27017/bd"
      PORT: "5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    environment:
      REACT_APP_API: "http://localhost:5000"
    depends_on:
      - backend
